# æœºåœºè®¢é˜…
proxy-providers:
  Airport1:
    url: "https://oooooooxxxxxxxxxxxxx?clash=1"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿
  Airport2:
    url: "https://xxxxxxxxoooooooo?clash=1"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ğŸš€ é»˜è®¤ä»£ç†  

# èŠ‚ç‚¹ä¿¡æ¯
proxies:
  - {name: ç›´è¿, type: direct}

# å…¨å±€é…ç½® 
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
bind-address: "*"
ipv6: false
unified-delay: true
tcp-concurrent: true
log-level: warning
find-process-mode: 'off'
# interface-name: en0
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
disable-keep-alive: false
profile:
  store-selected: true
  store-fake-ip: true

# æ§åˆ¶é¢æ¿
external-controller: 0.0.0.0:9090
secret: ""
external-ui: "/etc/nikki/run"
external-ui-name: zashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

# å—…æ¢
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "+.baidu.com"

# å…¥ç«™  
tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

# DNSæ¨¡å—
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:private_domain,cn_domain,bank_cn_domain,ai_cn_domain,xiaomi_domain,media_cn_domain,apple_cn_domain,steam_cn_domain"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "time.*.com"
  default-nameserver:
    - 223.5.5.5
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
  # nameseverå°½é‡ç”¨è¿è¥å•†æä¾›çš„DNS
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
 
# å‡ºç«™ç­–ç•¥
# æ³¨æ„é”šç‚¹å¿…é¡»æ”¾åœ¨å¼•ç”¨çš„ä¸Šæ–¹ï¼Œå¯ä»¥é›†ä¸­æŠŠé”šç‚¹å…¨éƒ¨æ”¾yamlçš„é¡¶éƒ¨ã€‚
pr: &pr {type: select, proxies: [ğŸš€ é»˜è®¤ä»£ç†, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, ğŸ‡¹ğŸ‡¼ å°æ¹¾è‡ªåŠ¨, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡è‡ªåŠ¨, ğŸ‡°ğŸ‡· éŸ©å›½è‡ªåŠ¨, ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, ğŸ‡ºğŸ‡² ç¾å›½è‡ªåŠ¨, ğŸŒ å…¶ä»–å›½å®¶, ğŸŒ æ‰€æœ‰èŠ‚ç‚¹, ç›´è¿]}
proxy-groups:
  - {name: ğŸš€ é»˜è®¤ä»£ç†, type: select, proxies: [ â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, ğŸ‡¹ğŸ‡¼ å°æ¹¾è‡ªåŠ¨, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡è‡ªåŠ¨, ğŸ‡°ğŸ‡· éŸ©å›½è‡ªåŠ¨, ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, ğŸ‡ºğŸ‡² ç¾å›½è‡ªåŠ¨,  ğŸŒ å…¶ä»–å›½å®¶ , ğŸŒ æ‰€æœ‰èŠ‚ç‚¹, ç›´è¿]}
  - {name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "^((?!(ç›´è¿)).)*$"}
  - {name: YouTube, <<: *pr, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/youtube.png"}
  - {name: Google, <<: *pr, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/google.png"}
  - {name: ChatGPT, <<: *pr, icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/ChatGPT.png"}
  - {name: Meta, <<: *pr, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/meta.png"}
  - {name: twitter, <<: *pr, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/twitter.png"}
  - {name: æ•°å­—è´§å¸, <<: *pr, icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Cryptocurrency_2.png"}
  - {name: GitHub, <<: *pr, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/github.png"}
  - {name: TikTok, <<: *pr, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/tiktok.png"}
  - {name: Telegram, <<: *pr, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/telegram.png"}
  - {name: Line, <<: *pr, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/line.png"}
  - {name: NETFLIX, <<: *pr, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/3343ab556e28f94f1a000ee4a7123aa3ca7ed731/icon/netfix.png"}
  - {name: DisneyPlus, <<: *pr, icon: "https://raw.githubusercontent.com/Orz-3/mini/refs/heads/master/Color/DisneyPlus.png"}
  - {name: AppleTV, <<: *pr, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/appletv.png"}
  - {name: PayPal, <<: *pr, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/paypal.png"}
  - {name: STEAM, <<: *pr, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/steam.png"}
  - {name: å“”å“©å“”å“©,  <<: *pr, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/bilibili.png"}
  - {name: å›½å†…åª’ä½“, type: select, proxies: [ç›´è¿, ğŸš€ é»˜è®¤ä»£ç†],icon: "https://raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/DomesticMedia.png"}
  - {name: å¾®è½¯ç¡¬ç›˜, <<: *pr, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/onedrive.png"}
  - {name: å¾®è½¯, <<: *pr, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/microsoft.png"}
  - {name: Speedtest, <<: *pr, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/speedtest.png"}
  - {name: è‹¹æœ, type: select, proxies: [ç›´è¿, ğŸš€ é»˜è®¤ä»£ç†],icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/apple.png"}
  - {name: æ¸¸æˆå¹³å°, type: select, proxies: [ç›´è¿, ğŸš€ é»˜è®¤ä»£ç†], icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/game.png"}
  - {name: ğŸ¯ ç›´è¿, type: select, proxies: [ç›´è¿, ğŸš€ é»˜è®¤ä»£ç†]}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, <<: *pr}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"}
  - {name: ğŸ‡¹ğŸ‡¼ å°æ¹¾è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?=.*(å°|TW|(?i)Taiwan))^((?!(æ¸¯|æ—¥|éŸ©|æ–°|ç¾)).)*$"}
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?=.*(æ–°|SG|(?i)Singapore))^((?!(æ¸¯|å°|æ—¥|éŸ©|ç¾)).)*$"}
  - {name: ğŸ‡°ğŸ‡· éŸ©å›½è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?=.*(éŸ©|KR|(?i)Korea))^((?!(æ¸¯|å°|æ—¥|æ–°|ç¾)).)*$"}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?=.*(æ—¥|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$" }
  - {name: ğŸ‡ºğŸ‡² ç¾å›½è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?=.*(ç¾|US|(?i)States|America))^((?!(æ¸¯|å°|æ—¥|éŸ©|æ–°)).)*$"}
  - {name: ğŸŒ å…¶ä»–å›½å®¶, type: select, include-all: true, filter: "^((?!(æ¸¯|hk|hongkong|hong kong|å°|ğŸ‡¹ğŸ‡¼|tw|taiwan|æ–°|ğŸ‡¸ğŸ‡¬|sg|singapore|æ—¥|jp|japan|ç¾|us|unitedstates|united states|éŸ©|ğŸ‡°ğŸ‡·|kr|korea|ç›´è¿)).)*$"}
  - {name: ğŸŒ æ‰€æœ‰èŠ‚ç‚¹, type: select, include-all: true}

# è§„åˆ™åŒ¹é…
# æ­¤è§„åˆ™éƒ¨åˆ†æ²¡æœ‰åšé˜²æ³„éœ²å¤„ç†ï¼Œå› ä¸ºå¼Šä¸¥é‡å¤§äºåˆ©ï¼
rules:
  - DOMAIN-KEYWORD,sev7en.blog,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,banAd_domain,ğŸ¯ ç›´è¿
  - RULE-SET,private_domain,ğŸ¯ ç›´è¿
  - RULE-SET,bank_cn_domain,ğŸ¯ ç›´è¿
  - RULE-SET,xiaomi_domain,ğŸ¯ ç›´è¿
  - RULE-SET,ai_cn_domain,ğŸ¯ ç›´è¿
  - RULE-SET,apple_cn_domain,è‹¹æœ
  - RULE-SET,proxylite,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,ai,ChatGPT
  - RULE-SET,openai_domain,ChatGPT
  - RULE-SET,github_domain,GitHub
  - RULE-SET,youtube_domain,YouTube
  - RULE-SET,google_domain,Google
  - RULE-SET,crypto_domain,æ•°å­—è´§å¸
  - RULE-SET,twitter_domain,twitter
  - RULE-SET,facebook_domain,Meta
  - RULE-SET,whatsapp_domain,Meta
  - RULE-SET,instagram_domain,Meta
  - RULE-SET,threads_domain,Meta
  - RULE-SET,meta_domain,Meta
  - RULE-SET,line_domain,Line
  - RULE-SET,onedrive_domain,å¾®è½¯ç¡¬ç›˜
  - RULE-SET,microsoft_domain,å¾®è½¯
  - RULE-SET,tiktok_domain,TikTok
  - RULE-SET,media_cn_domain,å›½å†…åª’ä½“
  - RULE-SET,media!cn_domain,å›½å†…åª’ä½“
  - RULE-SET,steam_domain,STEAM
  - RULE-SET,steam_cn_domain,ğŸ¯ ç›´è¿
  - RULE-SET,steamcdn_domain,ğŸ¯ ç›´è¿
  - RULE-SET,steamcdn_ip,ğŸ¯ ç›´è¿,no-resolve
  - RULE-SET,Epic_domain,æ¸¸æˆå¹³å°
  - RULE-SET,EA_domain,æ¸¸æˆå¹³å°
  - RULE-SET,Blizzard_domain,æ¸¸æˆå¹³å°
  - RULE-SET,UBI_domain,æ¸¸æˆå¹³å°
  - RULE-SET,Sony_domain,æ¸¸æˆå¹³å°
  - RULE-SET,Nintendo_domain,æ¸¸æˆå¹³å°
  - RULE-SET,speedtest_domain,Speedtest
  - RULE-SET,bilibili_domain,å“”å“©å“”å“©
  - RULE-SET,bilibili_ip,å“”å“©å“”å“©,no-resolve
  - RULE-SET,telegram_domain,Telegram
  - RULE-SET,netflix_domain,NETFLIX
  - RULE-SET,appleTV_domain,AppleTV
  - RULE-SET,disney_domain,DisneyPlus
  - RULE-SET,paypal_domain,PayPal
  - RULE-SET,gfw_domain,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,geolocation-!cn,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,cn_domain,ğŸ¯ ç›´è¿
  - RULE-SET,twitter_ip,twitter,no-resolve
  - RULE-SET,facebook_ip,Meta,no-resolve
  - RULE-SET,google_ip,Google,no-resolve
  - RULE-SET,netflix_ip,NETFLIX,no-resolve
  - RULE-SET,telegram_ip,Telegram,no-resolve
  - RULE-SET,private_ip,ğŸ¯ ç›´è¿,no-resolve
  - RULE-SET,cn_ip,ğŸ¯ ç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

# è§„åˆ™é›†
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  banAd_domain: { <<: *domain, url: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/rules/Domain/banAd.mrs" }
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  bank_cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-bank-cn.mrs" }
  xiaomi_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/xiaomi.mrs" }
  proxylite: { <<: *class, url: "https://raw.githubusercontent.com/ifanrBook/ClashConfig/refs/heads/main/proxy.list"}
  ai: {  <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-!cn.mrs" }
  openai_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/openai.mrs" }
  ai_cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-ai-cn.mrs" }
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  appleTV_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/apple-tvplus.mrs"}
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  facebook_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/facebook.mrs" }
  whatsapp_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/whatsapp.mrs" }
  instagram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/instagram.mrs" }       
  threads_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/threads.mrs" }
  twitter_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/twitter.mrs" }
  crypto_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-cryptocurrency.mrs" }
  meta_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/meta.mrs"}
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  line_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/line.mrs" }
  netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  disney_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/disney.mrs" }
  paypal_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  onedrive_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
  microsoft_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  steam_cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/steam@cn.mrs" }
  steamcdn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/rules/Domain/Steam-domain.mrs" }
  steam_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/steam.mrs" }
  Epic_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/epicgames.mrs" }
  EA_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/ea.mrs" }
  Blizzard_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/blizzard.mrs" }
  UBI_domain: { <<: *domain, url: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/rules/Domain/ubi.mrs" }
  Sony_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/sony.mrs" }
  Nintendo_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/nintendo.mrs" }
  apple_cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs"}
  speedtest_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
  bilibili_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/bilibili.mrs" }
  tiktok_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
  media_cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-media-cn.mrs" }
  media!cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-social-media-!cn.mrs" }
  gfw_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs"}
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  bilibili_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo-lite/geoip/bilibili.mrs" }
  private_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/private.mrs" }
  facebook_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/facebook.mrs" }
  steamcdn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/rules/IP/steamCDN-ip.mrs" }
  twitter_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/twitter.mrs" }                                               
